### ISSUE TITLE
Calculation never ends. Errors have little information.

### ISSUE THREAD

**Issue by RonYanDaik** [pietru2004/Godot-WFC#3]
Calculation does not end, How do i figure out what i did wrong?
Picture: left - calculation , right - painted rules.

![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/f7ad8b65-780b-4286-afa2-bdedcea8cb9c)

What do this errors mean?
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/177e3fa5-140b-437f-a38b-17c56e49747b)

**Comment by pietru2004** [comment]
the debug shows last cell that had 0 possible outcomes 
array:
element 0 - position of cell
element 1 shows arrays from surrounding cells (6 sides of cube)
element 2 arrays that were used to compare cells

Also it works, but if you have many cells and small ruleset it will be harder...

try looking at demo - my way of doing stuff was clearing gridmap or editing what was generated when it was having problems and painting by hand and then adding rules with rule add mode.

**Comment by pietru2004** [comment]
Depending on tile set and rules it can take from 57(small ammount) up to (undefined ammount, 4000+) of map generation errors.
Try smaller map sizes - that are more likely to generate with no errors and make it easier to spot problems/rule problems
Make Delay Between Tries bigger (seconds)
Starter tiles are taken from mesh lib definer -> mesh lib data, so you do not need to regenerate rules for them
Remember to check is your grass tile ignoring rotation, if it does not ignore rotation then well it can be source of problems

**Comment by RonYanDaik** [comment]
It got stuck again with this ruleset.

![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/d9c2632f-0a44-4c26-8006-1885ebeea632)
It feels like it shouldn't have problem with this tileset. Every piece has `ignore rotation = off`

**Comment by pietru2004** [comment]
it's problem is that
straight road knows it can have grass z-
straight does not know it can have road z+

**Comment by pietru2004** [comment]
rule can be 2 tiles placed next to each other
try placing somewhere
grass -  road - grass

**Comment by RonYanDaik** [comment]
Im not sure how its working, but, Maybe it will be a good idea to add sort
of "safe mod" when algorithm will pick next cell with least amount of
variants?

**Comment by pietru2004** [comment]
you can disable conflict_repair, if there is place where it can't place any cell it will stop running, as for safe mode... I can think about it, mayby make conflict repair conflict resolving with options stop running, skip, try repair...

also see this
![obraz](https://github.com/pietru2004/Godot-WFC/assets/51274570/35bd8484-c0bb-48b1-b36a-abd5cbc71a62)
it would resolve problems, but it would take some time...
you could try setting delay to 0.001 or just 0 - run every frame, clear console, start generation, go mayby eat something (remembering to leave focus on godot, or it will slow engine running speed) and come back and hopefully have result...

**Comment by RonYanDaik** [comment]
Couple of observings.
I've noticed persistent pattern. At some point at row 15 (its not an edge, area is 20x20)  algorithm stops calculating diagonal and goes along red arrow which always leads to errors since 2 regions begin to fight each other.
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/04365862-6045-4466-b5db-166abe6a66de)

After that it starts to pick cells that will lead to the errors.

![errors](https://github.com/pietru2004/Godot-WFC/assets/3350340/f779e62d-4dd3-4a9d-b4d4-0b920a27d62b)

If it would've picked blue ones that could be avoided. Also blue once should have less available options.
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/ff9c7e15-e484-420a-8b39-a2371349c4b4)

Can you tell which part of code is responsible for deciding which cell to pick next?

**Comment by RonYanDaik** [comment]
> it would resolve problems, but it would take some time...

No, it doesn't looks like it will. Its stuck in same one cell forever.

**Comment by pietru2004** [comment]
It is supposed to select based on sorting of cells and take cell 0 from array...

**Comment by RonYanDaik** [comment]
With size of 16 it works fine. But when i set size to 17 almost it always breaks.

**Comment by RonYanDaik** [comment]
> It is supposed to select based on sorting of cells and take cell 0 from array...

Is this it?
```
func sort_entropy(a, b):
	print ("a:",a, " b:",b)
	return (a[1] < b[1]) and !(a[1]<=0)
```

**Comment by pietru2004** [comment]
now that I look at this I docalc entropy but I don't apply it anywhere...
func calc_celc_entropy, seams I forgot to use data from entropy calc...

**Comment by pietru2004** [comment]
please check new update - I was getting consistent 1 confilict repair... no more... (demo2) (demo1 was getting bit more cause area is 10 on 20)

**Comment by RonYanDaik** [comment]
Now it works better if i enable only one starter tile - green grass tile.
If i have more enabled it gets stuck again.
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/6ef76f31-884d-4790-b23d-bf8fb9de7b49)

But now algorithm always go around first. Before it starts filling everything else. Which gives pretty similiar results. Which makes sense. It fills last row and since it has only 2 variants it pretty soon chooses end-of-road tile. And at that point its "locked" with the result.

I liked more previous behavior calculating in diagonals. Which game more variety in results.
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/6cfc3eb9-29e2-4fc2-b749-6ae1d1410ff2)

![wfc1](https://github.com/pietru2004/Godot-WFC/assets/3350340/14377f06-b725-4da0-9e12-3e657cae28c5)

**Comment by RonYanDaik** [comment]
But here is waht happens when it goes "other" direction.

![wfc2](https://github.com/pietru2004/Godot-WFC/assets/3350340/3fc2df48-95bf-4d62-aa1b-2f0cf5af338e)

It pick red position. Whit is already an error. Instead it should've picked one of the blues.
![image](https://github.com/pietru2004/Godot-WFC/assets/3350340/7680cff9-1b91-4c3a-935e-66ed88bda183)

It looks like you are calculating entropy only for adjacent tiles and do not propagate potential changes along the grid. Which leads to errors.

In other world you skip step of recalculating the entropy of the entire grid after placing a single tile.

**Comment by RonYanDaik** [comment]
> In other world you skip step of recalculating the entropy of the entire grid after placing a single tile.

Recalculating entire grid seems time consuming, but also is repairing of errors. that leads to mote time consuming calculation. Also you don't need to recalculate full grid, only those cells that are changing. It should lead to narrowing it to only 10% of grid recalculation.

**Comment by pietru2004** [comment]
it works on adding waiting tiles - it adds starter tile to waiting tiles, selects it and adds tiles that are on the sides, it favours side where is 1 tile or tile weight is higher, that is theory so if you have [1,1] and [3,1] the [3,1] should have lower entropy and be used first

this
![obraz](https://github.com/pietru2004/Godot-WFC/assets/51274570/3759e8ae-1ca1-4a35-b1a1-3eb83a6bbf3d)
gives this 
![obraz](https://github.com/pietru2004/Godot-WFC/assets/51274570/1f8aed0d-b4d8-47ac-8d55-da2b02ea146e)

mayby I should add check to get list of tiles with the same entropy and get random from them, and not always cell 0 from array

**Comment by pietru2004** [comment]
please try new demo_road_line - it is made to be similar with tile set you chose, also for your usecase I recomend t ocheck new cell sorting
![obraz](https://github.com/pietru2004/Godot-WFC/assets/51274570/f7d02bc4-87e7-4dbe-b986-b2cef88ee469)

**Comment by pietru2004** [comment]
@RonYanDaik I want to ask is the generator working now... If yes I will close issue...

**Comment by RonYanDaik** [comment]
For this case it works better. Yes.
