### ISSUE TITLE
Parser Error: Class "MeshLibDefiner::GetInterface" cannot be constructed as it is based on abstract native class "EditorScript".

### ISSUE THREAD

**Issue by stesproject** [pietru2004/Godot-WFC#5]
I get this error when I try to run the demo.
Godot version: 4.2.2

**Comment by pietru2004** [comment]
should be fixed in https://github.com/pietru2004/Godot-WFC/commit/a8fa141a4ba8d95dc7fb61075d98507b093f4c16
