### ISSUE TITLE
Can't add rules

### ISSUE THREAD

**Issue by n0ahwint3r** [pietru2004/Godot-WFC#7]
Whenever I click on the Add Element Button in the Mesh Lib Rule Set, Godot will print out "Item set", no bug report whatsoever but nothing else happens...
I probably just enabled/disabled some crucial option, but I can't figure out which one?

**Comment by pietru2004** [comment]
@n0ahwint3r you aren't supposed to edit Mesh Lib Rule Set rule set by hand.
After using Generate Meshlib you should be able to paint your rules. 
After that go and select do you want to add rules to current data set, if yes make sure that Add Mode is checked.
Next Use generate Rules btn to generate Mesh Lib Rule Set.
Also Remember to disengage Generation Lock, the safety feauture.
